### ISSUE TITLE
Thoughts on returning a removal function instead? 

### ISSUE THREAD

**Issue by tannerlinsley** [boschni/normalized-cache#3]
https://github.com/boschni/normalized-cache/blob/c3c69047ad33f37175e9aabc4bf022c7cf9b7aec/src/Cache.ts#L245

I tend to enjoy the cleanup function style  returned by other APIs. Would that be a good fit here?

**Comment by boschni** [comment]
The rationale is that it allows consumers to store the optimistic update ID somewhere in a "redux' store for example. But maybe this is not really needed, and it does diverge from the other functions that return dispose functions. What do you think?

**Comment by tannerlinsley** [comment]
I think I could go either way. In fact, I did see an API recently that offered both. I can't recall exactly, but I remember it being something like this:

```js
const [unsubscribe, id] = api.subscribe()

// Either
unsubscribe()
// or
api.unsubscribe(id)
```

I personally have never needed to store a sub reference in a serialized way, so 🤷

**Comment by boschni** [comment]
Added `Disposable` and `Unubscribable` objects to support both use cases :)
